title: Afilando piedras
email: emoriarty81@gmail.com
description: > 
  En este blog está dedicado a conceptos, ideas y soluciones a cuestiones relacionados con la programación, orientado principalmente a Front-end.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: emoriarty81
github_username:  emoriarty
permalink: /:title
# Build settings
destination: docs
markdown: kramdown
## Also using https://github.com/penibelst/jekyll-compress-html
gems:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-gist
  - jekyll_inline_highlight
exclude:
  - Gemfile
  - Gemfile.lock
  - build.sh
  - build.prod.sh
  - serve.sh
keep_files:
  - CNAME
  - assets
pagination:
  enabled: true
  per_page: 10
  permalink: '/:num/'
  sort_reverse: true
  title: 'Nocturnidades (:num)'
  trail: 
    before: 2
    after: 2
autopages:
  enabled: true
  collections:
    enabled: false
  categories: 
    layouts: 
      - 'autopages.html'
    title: '<span class="category-title">:cat</span>'
    permalink: '/categoria/:cat'
  tags:
    layouts: 
      - 'autopages.html'
    title: '<span class="tag-title">:tag</span>'
    permalink: '/tag/:tag'
compress_html:
  clippings: []
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: true
  startings: []

# Server
host: 0.0.0.0

defaults:
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: relatos
    values:
      layout: tale
