title: Nocturnidades
html_title: N<i>octurnidades</i>
email: emoriarty81@gmail.com
description: > 
  La intención inicial de este blog es publicar y compartir relatos, ideas y 
  tribulaciones varias. También tienen cabida documentos técnicos relacionados 
  con la programación.
  El título del blog hace referencia al único momento del día (de la noche) 
  en que los artículos son perpetrados.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: emoriarty81
github_username:  emoriarty
permalink: /:title
# Build settings
destination: docs
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
  - build.sh
  - build.prod.sh
  - serve.sh
keep_files:
  - CNAME
  - assets
collections:
  relatos:
    output: true
# paging
pagination:
  enabled: true
  per_page: 5
  permalink: '/:num/'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

# Server
host: 0.0.0.0

defaults:
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: relatos
    values:
      layout: tale
